# Generated by Django 4.1.3 on 2022-12-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='livro')),
                ('abbreviation', models.CharField(max_length=3, verbose_name='abreviação')),
                ('testament', models.CharField(choices=[('old', 'antigo'), ('new', 'novo')], max_length=3, verbose_name='testemunho')),
            ],
            options={
                'verbose_name': 'livro',
                'verbose_name_plural': 'livros',
                'ordering': ('testament', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'leitura',
                'verbose_name_plural': 'leituras',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Versicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='capítulo')),
                ('number', models.IntegerField(verbose_name='número')),
                ('text', models.TextField(max_length=255, verbose_name='texto')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.book', verbose_name='livro')),
                ('lection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lection', verbose_name='leitura')),
            ],
            options={
                'verbose_name': 'versículo',
                'verbose_name_plural': 'versículos',
                'ordering': ('book__testament', 'book__name', 'chapter', 'number'),
            },
        ),
    ]
