# Generated by Django 4.1.3 on 2022-12-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Versicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=150, verbose_name='nome')),
                ('book_abbreviation', models.CharField(max_length=3, verbose_name='abreviação')),
                ('chapter', models.IntegerField(verbose_name='capítulo')),
                ('number', models.IntegerField(verbose_name='versículo')),
                ('text', models.TextField(max_length=255, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'versículo',
                'verbose_name_plural': 'versículos',
            },
        ),
    ]
