# Generated by Django 4.1.3 on 2022-12-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='abbreviation',
            field=models.CharField(max_length=4, verbose_name='abreviação'),
        ),
    ]
