# Generated by Django 4.1.3 on 2022-12-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('testament', 'name'), 'verbose_name': 'livro', 'verbose_name_plural': 'livros'},
        ),
        migrations.AlterModelOptions(
            name='versicle',
            options={'ordering': ('book__testament', 'book__name', 'chapter', 'number'), 'verbose_name': 'versículo', 'verbose_name_plural': 'versículos'},
        ),
        migrations.AlterField(
            model_name='versicle',
            name='chapter',
            field=models.IntegerField(verbose_name='capítulo'),
        ),
        migrations.AlterField(
            model_name='versicle',
            name='number',
            field=models.IntegerField(verbose_name='número'),
        ),
    ]
