# Generated by Django 4.1.3 on 2022-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versicle',
            name='book',
            field=models.CharField(max_length=150, verbose_name='livro'),
        ),
        migrations.AlterField(
            model_name='versicle',
            name='book_abbreviation',
            field=models.CharField(max_length=3, verbose_name='abreviação do livro'),
        ),
        migrations.AlterField(
            model_name='versicle',
            name='chapter',
            field=models.CharField(max_length=3, verbose_name='capítulo'),
        ),
        migrations.AlterField(
            model_name='versicle',
            name='number',
            field=models.CharField(max_length=3, verbose_name='versículo'),
        ),
    ]
