# Generated by Django 4.1.3 on 2022-12-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_versicle_book_alter_versicle_book_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'leitura',
                'verbose_name_plural': 'leituras',
            },
        ),
        migrations.AddField(
            model_name='versicle',
            name='lection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lection', verbose_name='leitura'),
        ),
    ]
