# Generated by Django 4.1.3 on 2022-12-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_task_options_task_completed_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='ordem'),
        ),
    ]
