# Generated by Django 4.1.3 on 2022-12-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_lection_versicle_lection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lection',
            options={'ordering': ('order',), 'verbose_name': 'leitura', 'verbose_name_plural': 'leituras'},
        ),
        migrations.AlterField(
            model_name='versicle',
            name='book_abbreviation',
            field=models.CharField(max_length=3, verbose_name='abreviação'),
        ),
    ]
