# Generated by Django 4.1.3 on 2022-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versicle',
            options={'ordering': ('book',), 'verbose_name': 'versículo', 'verbose_name_plural': 'versículos'},
        ),
        migrations.RemoveField(
            model_name='lection',
            name='completed',
        ),
        migrations.AlterField(
            model_name='lection',
            name='order',
            field=models.IntegerField(verbose_name='ordem'),
        ),
    ]
