# Generated by Django 4.1.3 on 2022-12-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_versicle_options_remove_lection_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='versicle',
            options={'ordering': ('book', 'chapter'), 'verbose_name': 'versículo', 'verbose_name_plural': 'versículos'},
        ),
    ]
